version: '3.8'
services:
  ecliptix:
    build:
      context: .
      dockerfile: Ecliptix.Core/Dockerfile
    ports:
      - "5051:5051"
    environment:
      - ASPNETCORE_URLS=http://+:5051
      - ASPNETCORE_ENVIRONMENT=Production