- hosts: jenkins
  become: true
  vars:
    jenkins_user: jenkins
    jenkins_port: 10001
    github_host: "github.com"

  tasks:
    - name: Ensure Jenkins user exists
      user:
        name: "{{ jenkins_user }}"
        home: /var/lib/jenkins
        shell: /bin/bash
        create_home: yes

    - name: Install python-jenkins via apt
      ansible.builtin.apt:
        name: python3-jenkins
        state: present
        update_cache: yes

    - name: Add Jenkins key
      shell: curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Add Jenkins apt repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Ensure systemd override directory exists
      file:
        path: /etc/systemd/system/jenkins.service.d
        state: directory

    - name: Override Jenkins port
      copy:
        dest: /etc/systemd/system/jenkins.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          Environment="JENKINS_PORT={{ jenkins_port }}"
          ExecStart=/usr/bin/java -Djava.awt.headless=true -jar /usr/share/java/jenkins.war --webroot=/var/cache/jenkins/war --httpPort={{ jenkins_port }}

    - name: Ensure Jenkins SSH directory exists
      file:
        path: "/var/lib/jenkins/.ssh"
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        mode: "0700"

    - name: Add GitHub to known_hosts
      known_hosts:
        path: "/var/lib/jenkins/.ssh/known_hosts"
        name: "{{ github_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 ' + github_host) }}"
        state: present
      become_user: "{{ jenkins_user }}"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Ensure Jenkins service is enabled and started
      systemd:
        name: jenkins
        state: restarted
        enabled: true

    - name: Wait for Jenkins HTTP port to be up
      wait_for:
        host: localhost
        port: "{{ jenkins_port }}"
        timeout: 120
        state: started
        
    - name: Create buildx builder for Jenkins
      become_user: jenkins
      shell: |
        docker buildx create --name mybuilder --use || true
        docker buildx inspect mybuilder || docker buildx ls
