- hosts: jenkins
  become: true
  vars:
    github_private_key: "{{ lookup('file', env_vars.GITHUB_SSH_KEY_PATH) }}"
  tasks:
    - name: Create GitHub pipeline job via Groovy
      community.general.jenkins_script:
        url: "{{ env_vars.JENKINS_URL }}"
        user: "{{ env_vars.JENKINS_USER }}"
        password: "{{ env_vars.JENKINS_PASS }}"
        script: |
          import jenkins.model.*
          import org.jenkinsci.plugins.workflow.job.WorkflowJob
          import org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition
          import hudson.plugins.git.*
          import hudson.plugins.git.extensions.impl.*
          import hudson.plugins.git.util.*
          import hudson.plugins.git.browser.*
          import hudson.plugins.git.traits.*
          import com.cloudbees.plugins.credentials.CredentialsProvider
          import com.cloudbees.plugins.credentials.CredentialsMatchers
          import com.cloudbees.plugins.credentials.common.StandardUsernameCredentials
          import com.cloudbees.plugins.credentials.domains.DomainRequirement
          import java.util.Collections
          
          def jenkins = Jenkins.instance
          def jobName = "memberships-pipeline"
          def gitRepo = "git@github.com:oleksandrmelnychenko/Ecliptix-Web-Server.git"
          def credentialsId = "github-ssh-key"
          def jenkinsfilePath = "Jenkinsfile"
          
          def job = jenkins.getItem(jobName)
          if (job == null) {
            job = jenkins.createProject(WorkflowJob, jobName)
          }
          
          def userRemoteConfig = new UserRemoteConfig(gitRepo, null, null, credentialsId)
          def gitSCM = new GitSCM(
            [userRemoteConfig],
            [new BranchSpec("*/main")],
            false,
            Collections.<SubmoduleConfig>emptyList(),
            null,
            null,
            [new CleanCheckout()]
          )
          
          def flowDef = new CpsScmFlowDefinition(gitSCM, jenkinsfilePath)
          flowDef.lightweight = true
          job.setDefinition(flowDef)
          
          import org.jenkinsci.plugins.github_branch_source.GitHubSCMSource
          import jenkins.branch.BranchSource
          import jenkins.branch.MultiBranchProject
          import jenkins.model.JenkinsLocationConfiguration
          
          job.save()
          println "Job '${jobName}' створено/оновлено!"


