- import_playbook: import_env_vars.yml
- import_playbook: dependencies.yml
- import_playbook: docker.yml
- import_playbook: jenkins.yml
- import_playbook: jenkins_creds.yml
- import_playbook: jenkins_jobs.yml
- import_playbook: nginx.yml