syntax = "proto3";

package ecliptix.transport.device_provisioning;
option csharp_namespace = "Ecliptix.Protobuf.Transport.DeviceProvisioning";

enum DeviceProvisioningEventType {
  DEVICE_PROVISIONING_EVENT_TYPE_UNSPECIFIED = 0;
  DEVICE_PROVISIONING_REGISTER_DEVICE = 1;
  DEVICE_PROVISIONING_SECURE_CHANNEL_ESTABLISH = 2;
  DEVICE_PROVISIONING_SECURE_CHANNEL_RESTORE = 3;
  DEVICE_PROVISIONING_SECURE_CHANNEL_AUTH_ESTABLISH = 4;
}

message RestoreChannelRequest {}

message RestoreChannelResponse {
  enum Status {
    STATUS_UNSPECIFIED = 0;
    SESSION_NOT_FOUND = 1;
    SESSION_RESTORED = 2;
  }

  Status status = 1;
  int32 sending_chain_length = 2;
  int32 receiving_chain_length = 3;
}

message AuthenticatedEstablishRequest {
  bytes membership_unique_id = 1;
  bytes account_unique_id = 2;
  bytes master_key_fingerprint = 3;
  bytes client_pub_key_exchange = 4;
}
