namespace Ecliptix.IdentityAccess.Domain.Memberships.WorkerActors.VerificationFlow.PersistenceModels;

internal sealed record VerificationFlowStatePersistedEvent(VerificationFlowPersistentState State);
