<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka" />
    <PackageReference Include="Akka.Persistence.Sql" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Grpc.AspNetCore.Server" />
    <PackageReference Include="libphonenumber-csharp" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Otp.NET" />
    <PackageReference Include="Polly" />
    <PackageReference Include="protobuf-net" />
    <PackageReference Include="protobuf-net.Grpc" />
    <PackageReference Include="Protobuf.Grpc" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pixelbin" />
    <PackageReference Include="protobuf-net.Grpc.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Twilio.AspNet.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Ecliptix.IdentityAccess.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Ecliptix.SharedKernel\Ecliptix.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\..\Ecliptix.Security.Opaque\Ecliptix.Security.Opaque.csproj" />
    <ProjectReference Include="..\..\..\..\Ecliptix.Protobufs\Ecliptix.Protobufs.csproj" />
  </ItemGroup>
</Project>
