<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>Ecliptix.Security.Certificate.Pinning</AssemblyName>
        <RootNamespace>Ecliptix.Security.Certificate.Pinning</RootNamespace>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ecliptix.Pinning.Relay" Version="1.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\Shared\Ecliptix.SharedKernel\Ecliptix.SharedKernel.csproj" />
    </ItemGroup>

</Project>
