//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecliptix.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VerificationFlowRes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VerificationFlowRes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ecliptix.Core.Resources.VerificationFlowRes", typeof(VerificationFlowRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string verification_flow_conflict_resolved_to_existing {
            get {
                return ResourceManager.GetString("verification_flow_conflict_resolved_to_existing", resourceCulture);
            }
        }
        
        public static string verification_flow_conflict_unresolved {
            get {
                return ResourceManager.GetString("verification_flow_conflict_unresolved", resourceCulture);
            }
        }
        
        public static string verification_flow_reused_and_updated {
            get {
                return ResourceManager.GetString("verification_flow_reused_and_updated", resourceCulture);
            }
        }
        
        public static string verification_flow_conflict {
            get {
                return ResourceManager.GetString("verification_flow_conflict", resourceCulture);
            }
        }
        
        public static string verification_flow_expired {
            get {
                return ResourceManager.GetString("verification_flow_expired", resourceCulture);
            }
        }
        
        public static string verification_flow_not_found {
            get {
                return ResourceManager.GetString("verification_flow_not_found", resourceCulture);
            }
        }
        
        public static string verification_flow_not_verified {
            get {
                return ResourceManager.GetString("verification_flow_not_verified", resourceCulture);
            }
        }
        
        public static string verification_session_not_found {
            get {
                return ResourceManager.GetString("verification_session_not_found", resourceCulture);
            }
        }
        
        public static string otp_invalid {
            get {
                return ResourceManager.GetString("otp_invalid", resourceCulture);
            }
        }
        
        public static string otp_expired {
            get {
                return ResourceManager.GetString("otp_expired", resourceCulture);
            }
        }
        
        public static string otp_generation_failed {
            get {
                return ResourceManager.GetString("otp_generation_failed", resourceCulture);
            }
        }
        
        public static string otp_max_attempts_reached {
            get {
                return ResourceManager.GetString("otp_max_attempts_reached", resourceCulture);
            }
        }
        
        public static string otp_not_verified {
            get {
                return ResourceManager.GetString("otp_not_verified", resourceCulture);
            }
        }
        
        public static string phone_invalid {
            get {
                return ResourceManager.GetString("phone_invalid", resourceCulture);
            }
        }
        
        public static string sms_send_failed {
            get {
                return ResourceManager.GetString("sms_send_failed", resourceCulture);
            }
        }
        
        public static string data_concurrency_conflict {
            get {
                return ResourceManager.GetString("data_concurrency_conflict", resourceCulture);
            }
        }
        
        public static string data_access_failed {
            get {
                return ResourceManager.GetString("data_access_failed", resourceCulture);
            }
        }
        
        public static string security_rate_limit_exceeded {
            get {
                return ResourceManager.GetString("security_rate_limit_exceeded", resourceCulture);
            }
        }
        
        public static string security_suspicious_activity {
            get {
                return ResourceManager.GetString("security_suspicious_activity", resourceCulture);
            }
        }
        
        public static string membership_too_many_attempts {
            get {
                return ResourceManager.GetString("membership_too_many_attempts", resourceCulture);
            }
        }
        
        public static string signin_too_many_attempts {
            get {
                return ResourceManager.GetString("signin_too_many_attempts", resourceCulture);
            }
        }
        
        public static string activity_status_invalid {
            get {
                return ResourceManager.GetString("activity_status_invalid", resourceCulture);
            }
        }
        
        public static string app_device_created_but_invalid_id {
            get {
                return ResourceManager.GetString("app_device_created_but_invalid_id", resourceCulture);
            }
        }
        
        public static string app_device_invalid_id {
            get {
                return ResourceManager.GetString("app_device_invalid_id", resourceCulture);
            }
        }
        
        public static string associated {
            get {
                return ResourceManager.GetString("associated", resourceCulture);
            }
        }
        
        public static string phone_cannot_be_empty {
            get {
                return ResourceManager.GetString("phone_cannot_be_empty", resourceCulture);
            }
        }
        
        public static string created_and_associated {
            get {
                return ResourceManager.GetString("created_and_associated", resourceCulture);
            }
        }
        
        public static string exists {
            get {
                return ResourceManager.GetString("exists", resourceCulture);
            }
        }
        
        public static string phone_number_not_found {
            get {
                return ResourceManager.GetString("phone_number_not_found", resourceCulture);
            }
        }
        
        public static string phone_not_found {
            get {
                return ResourceManager.GetString("phone_not_found", resourceCulture);
            }
        }
        
        public static string validation_failed {
            get {
                return ResourceManager.GetString("validation_failed", resourceCulture);
            }
        }
        
        public static string invalid_credentials {
            get {
                return ResourceManager.GetString("invalid_credentials", resourceCulture);
            }
        }
        
        public static string password_complexity_requirements {
            get {
                return ResourceManager.GetString("password_complexity_requirements", resourceCulture);
            }
        }
        
        public static string password_empty {
            get {
                return ResourceManager.GetString("password_empty", resourceCulture);
            }
        }
        
        public static string password_hash_error {
            get {
                return ResourceManager.GetString("password_hash_error", resourceCulture);
            }
        }
        
        public static string password_hash_input_empty {
            get {
                return ResourceManager.GetString("password_hash_input_empty", resourceCulture);
            }
        }
        
        public static string password_invalid_chars {
            get {
                return ResourceManager.GetString("password_invalid_chars", resourceCulture);
            }
        }
        
        public static string password_config_hash_algorithm_unsupported {
            get {
                return ResourceManager.GetString("password_config_hash_algorithm_unsupported", resourceCulture);
            }
        }
        
        public static string password_config_iterations_invalid {
            get {
                return ResourceManager.GetString("password_config_iterations_invalid", resourceCulture);
            }
        }
        
        public static string password_config_salt_size_invalid {
            get {
                return ResourceManager.GetString("password_config_salt_size_invalid", resourceCulture);
            }
        }
        
        public static string password_missing_digit {
            get {
                return ResourceManager.GetString("password_missing_digit", resourceCulture);
            }
        }
        
        public static string password_missing_lowercase {
            get {
                return ResourceManager.GetString("password_missing_lowercase", resourceCulture);
            }
        }
        
        public static string password_missing_special_char {
            get {
                return ResourceManager.GetString("password_missing_special_char", resourceCulture);
            }
        }
        
        public static string password_missing_uppercase {
            get {
                return ResourceManager.GetString("password_missing_uppercase", resourceCulture);
            }
        }
        
        public static string password_too_short {
            get {
                return ResourceManager.GetString("password_too_short", resourceCulture);
            }
        }
        
        public static string password_verify_base64_error {
            get {
                return ResourceManager.GetString("password_verify_base64_error", resourceCulture);
            }
        }
        
        public static string password_verify_error {
            get {
                return ResourceManager.GetString("password_verify_error", resourceCulture);
            }
        }
        
        public static string password_verify_hash_size_mismatch {
            get {
                return ResourceManager.GetString("password_verify_hash_size_mismatch", resourceCulture);
            }
        }
        
        public static string password_verify_input_empty {
            get {
                return ResourceManager.GetString("password_verify_input_empty", resourceCulture);
            }
        }
        
        public static string password_verify_invalid_format {
            get {
                return ResourceManager.GetString("password_verify_invalid_format", resourceCulture);
            }
        }
        
        public static string password_verify_mismatch {
            get {
                return ResourceManager.GetString("password_verify_mismatch", resourceCulture);
            }
        }
        
        public static string password_verify_salt_size_mismatch {
            get {
                return ResourceManager.GetString("password_verify_salt_size_mismatch", resourceCulture);
            }
        }
        
        public static string password_verify_stored_hash_empty {
            get {
                return ResourceManager.GetString("password_verify_stored_hash_empty", resourceCulture);
            }
        }
        
        public static string inactive_membership {
            get {
                return ResourceManager.GetString("inactive_membership", resourceCulture);
            }
        }
        
        public static string invalid_secure_key {
            get {
                return ResourceManager.GetString("invalid_secure_key", resourceCulture);
            }
        }
        
        public static string membership_already_exists {
            get {
                return ResourceManager.GetString("membership_already_exists", resourceCulture);
            }
        }
        
        public static string membership_not_found {
            get {
                return ResourceManager.GetString("membership_not_found", resourceCulture);
            }
        }
        
        public static string secure_key_cannot_be_empty {
            get {
                return ResourceManager.GetString("secure_key_cannot_be_empty", resourceCulture);
            }
        }
        
        public static string secure_key_not_set {
            get {
                return ResourceManager.GetString("secure_key_not_set", resourceCulture);
            }
        }
        
        public static string secure_key_too_long {
            get {
                return ResourceManager.GetString("secure_key_too_long", resourceCulture);
            }
        }
        
        public static string secure_key_updated {
            get {
                return ResourceManager.GetString("secure_key_updated", resourceCulture);
            }
        }
        
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        public static string generic_error {
            get {
                return ResourceManager.GetString("generic_error", resourceCulture);
            }
        }
        
        public static string generic_no_result_returned {
            get {
                return ResourceManager.GetString("generic_no_result_returned", resourceCulture);
            }
        }
        
        public static string generic_success {
            get {
                return ResourceManager.GetString("generic_success", resourceCulture);
            }
        }
        
        public static string generic_unexpected_outcome {
            get {
                return ResourceManager.GetString("generic_unexpected_outcome", resourceCulture);
            }
        }
        
        public static string phone_parsing_invalid_country_code {
            get {
                return ResourceManager.GetString("phone_parsing_invalid_country_code", resourceCulture);
            }
        }
        
        public static string phone_parsing_too_short {
            get {
                return ResourceManager.GetString("phone_parsing_too_short", resourceCulture);
            }
        }
        
        public static string phone_parsing_too_long {
            get {
                return ResourceManager.GetString("phone_parsing_too_long", resourceCulture);
            }
        }
        
        public static string phone_parsing_invalid_number {
            get {
                return ResourceManager.GetString("phone_parsing_invalid_number", resourceCulture);
            }
        }
        
        public static string phone_parsing_possible_but_local_only {
            get {
                return ResourceManager.GetString("phone_parsing_possible_but_local_only", resourceCulture);
            }
        }
        
        public static string phone_parsing_generic_error {
            get {
                return ResourceManager.GetString("phone_parsing_generic_error", resourceCulture);
            }
        }
        
        public static string phone_validation_unexpected_error {
            get {
                return ResourceManager.GetString("phone_validation_unexpected_error", resourceCulture);
            }
        }
    }
}
