//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecliptix.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VerificationFlowResource_uk_UA {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VerificationFlowResource_uk_UA() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ecliptix.Core.Resources.VerificationFlowResource_uk_UA", typeof(VerificationFlowResource_uk_UA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string verification_flow_session_not_found {
            get {
                return ResourceManager.GetString("verification_flow.session.not_found", resourceCulture);
            }
        }
        
        internal static string verification_flow_session_expired {
            get {
                return ResourceManager.GetString("verification_flow.session.expired", resourceCulture);
            }
        }
        
        internal static string verification_flow_session_conflict {
            get {
                return ResourceManager.GetString("verification_flow.session.conflict", resourceCulture);
            }
        }
        
        internal static string verification_flow_otp_invalid {
            get {
                return ResourceManager.GetString("verification_flow.otp.invalid", resourceCulture);
            }
        }
        
        internal static string verification_flow_otp_expired {
            get {
                return ResourceManager.GetString("verification_flow.otp.expired", resourceCulture);
            }
        }
        
        internal static string verification_flow_otp_max_attempts_reached {
            get {
                return ResourceManager.GetString("verification_flow.otp.max_attempts_reached", resourceCulture);
            }
        }
        
        internal static string verification_flow_otp_generation_failed {
            get {
                return ResourceManager.GetString("verification_flow.otp.generation_failed", resourceCulture);
            }
        }
        
        internal static string verification_flow_sms_send_failed {
            get {
                return ResourceManager.GetString("verification_flow.sms.send_failed", resourceCulture);
            }
        }
        
        internal static string verification_flow_phone_invalid {
            get {
                return ResourceManager.GetString("verification_flow.phone.invalid", resourceCulture);
            }
        }
        
        internal static string verification_flow_data_access_failed {
            get {
                return ResourceManager.GetString("verification_flow.data.access_failed", resourceCulture);
            }
        }
        
        internal static string verification_flow_data_concurrency_conflict {
            get {
                return ResourceManager.GetString("verification_flow.data.concurrency_conflict", resourceCulture);
            }
        }
        
        internal static string verification_flow_security_rate_limit_exceeded {
            get {
                return ResourceManager.GetString("verification_flow.security.rate_limit_exceeded", resourceCulture);
            }
        }
        
        internal static string verification_flow_security_suspicious_activity {
            get {
                return ResourceManager.GetString("verification_flow.security.suspicious_activity", resourceCulture);
            }
        }
        
        internal static string verification_flow_validation_failed {
            get {
                return ResourceManager.GetString("verification_flow.validation.failed", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_config_iterations_invalid {
            get {
                return ResourceManager.GetString("verification_flow.password.config.iterations_invalid", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_config_salt_size_invalid {
            get {
                return ResourceManager.GetString("verification_flow.password.config.salt_size_invalid", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_config_hash_algorithm_unsupported {
            get {
                return ResourceManager.GetString("verification_flow.password.config.hash_algorithm_unsupported", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_empty {
            get {
                return ResourceManager.GetString("verification_flow.password.empty", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_too_short {
            get {
                return ResourceManager.GetString("verification_flow.password.too_short", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_missing_lowercase {
            get {
                return ResourceManager.GetString("verification_flow.password.missing_lowercase", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_missing_uppercase {
            get {
                return ResourceManager.GetString("verification_flow.password.missing_uppercase", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_missing_digit {
            get {
                return ResourceManager.GetString("verification_flow.password.missing_digit", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_missing_special_char {
            get {
                return ResourceManager.GetString("verification_flow.password.missing_special_char", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_invalid_chars {
            get {
                return ResourceManager.GetString("verification_flow.password.invalid_chars", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_hash_input_empty {
            get {
                return ResourceManager.GetString("verification_flow.password.hash_input_empty", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_hash_error {
            get {
                return ResourceManager.GetString("verification_flow.password.hash_error", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_verify_input_empty {
            get {
                return ResourceManager.GetString("verification_flow.password.verify_input_empty", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_verify_stored_hash_empty {
            get {
                return ResourceManager.GetString("verification_flow.password.verify_stored_hash_empty", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_verify_invalid_format {
            get {
                return ResourceManager.GetString("verification_flow.password.verify_invalid_format", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_verify_base64_error {
            get {
                return ResourceManager.GetString("verification_flow.password.verify_base64_error", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_verify_salt_size_mismatch {
            get {
                return ResourceManager.GetString("verification_flow.password.verify_salt_size_mismatch", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_verify_hash_size_mismatch {
            get {
                return ResourceManager.GetString("verification_flow.password.verify_hash_size_mismatch", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_verify_mismatch {
            get {
                return ResourceManager.GetString("verification_flow.password.verify_mismatch", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_verify_error {
            get {
                return ResourceManager.GetString("verification_flow.password.verify_error", resourceCulture);
            }
        }
        
        internal static string verification_flow_password_complexity_requirements {
            get {
                return ResourceManager.GetString("verification_flow.password.complexity_requirements", resourceCulture);
            }
        }
        
        internal static string verification_flow_generic_error {
            get {
                return ResourceManager.GetString("verification_flow.generic.error", resourceCulture);
            }
        }
    }
}
