<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ecliptix.Protocol.Server" Version="1.0.0-ci.29" />
    <PackageReference Include="Sodium.Core" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Ecliptix.SharedKernel\Ecliptix.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\..\Ecliptix.Protobufs\Ecliptix.Protobufs.csproj" />
  </ItemGroup>
</Project>
