- hosts: jenkins
  become: true
  vars_files: 
    - group_vars/all.yml

  tasks:
    - name: Install dependencies
      apt:
        name:
          - fontconfig
          - openjdk-17-jdk
          - gnupg
          - curl
        state: present
        update_cache: yes

    - name: Add Jenkins key
      ansible.builtin.shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee \
        /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Add Jenkins apt repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins

    - name: Install Jenkins and tools
      apt:
        name:
          - jenkins
          - docker.io
          - git
        state: present
        update_cache: yes

    - name: Start and enable services
      systemd: 
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker
        - jenkins
